#!/usr/bin/env bash

# Setup environment variables for Docker
# This script auto-detects your user information

set -e

ENV_FILE=".env"

# Get current user information
CURRENT_UID=$(id -u)
CURRENT_GID=$(id -g)
CURRENT_USER=$(whoami)

echo "Detected user information:"
echo "  USER: $CURRENT_USER"
echo "  UID:  $CURRENT_UID"
echo "  GID:  $CURRENT_GID"
echo

# Check if .env exists
if [ -f "$ENV_FILE" ]; then
    echo ".env file already exists."
    
    # Check if USER, UID, GID are already set
    if grep -q "^USER=" "$ENV_FILE" && grep -q "^UID=" "$ENV_FILE" && grep -q "^GID=" "$ENV_FILE"; then
        echo "User configuration already present in .env"
        echo
        echo "Current values:"
        grep "^USER=" "$ENV_FILE"
        grep "^UID=" "$ENV_FILE"
        grep "^GID=" "$ENV_FILE"
        echo
        read -p "Do you want to update these values? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            echo "Keeping existing configuration."
            exit 0
        fi
        
        # Remove old values
        sed -i '/^USER=/d' "$ENV_FILE"
        sed -i '/^UID=/d' "$ENV_FILE"
        sed -i '/^GID=/d' "$ENV_FILE"
    fi
else
    echo "Creating .env file from .env.example..."
    cp .env.example "$ENV_FILE"
fi

# Add or update user configuration
echo "" >> "$ENV_FILE"
echo "# Auto-detected user configuration (generated by setup-env.sh)" >> "$ENV_FILE"
echo "USER=$CURRENT_USER" >> "$ENV_FILE"
echo "UID=$CURRENT_UID" >> "$ENV_FILE"
echo "GID=$CURRENT_GID" >> "$ENV_FILE"

echo
echo "✅ Environment configured successfully!"
echo
echo "Configuration written to $ENV_FILE:"
echo "  USER=$CURRENT_USER"
echo "  UID=$CURRENT_UID"
echo "  GID=$CURRENT_GID"
echo
echo "Next steps:"
echo "  1. Add your GITHUB_TOKEN to .env if not already set"
echo "  2. Run: ./utils rebuild"
echo "  3. Run: ./utils install"
